### ISSUE TITLE
an question? 

### ISSUE THREAD

**Issue by jellyr** [chzihan/A596#1]
https://github.com/chzihan/A596/blob/bbf8047eb4dfb798175c1800465f6d8b6a460985/HW7/a7_01.rkt#L56
should be
`(k^ (λ(a k) (k a) )) `
not
`(k^ k)`
I found this issue by test :

```
(lex
 `(let/cc k
       (k 3))
 `())

```
```
(value-of-cps
   '(letcc (app (var 0) (const 3)))
   (empty-env)
   (empty-k))

```
am I right?

**Comment by chzihan** [comment]
Thanks for your attention!

Well, I think that is mainly because my lex function doesn't produce the correct test result.
The test case given by the instructor looks like:
```
(value-of-cps '(letcc (const 5)) (empty-env) (empty-k))
(value-of-cps '(letcc (throw (var 0) (const 5))) (empty-env) (empty-k))
(value-of-cps '(letcc (throw (app (lambda (var 0)) (var 0)) 
                          (mult (const 5) (const 5))))
                          (empty-env) (empty-k))
```
Since k is a continuation, this lexical-address interpreter use 'throw together with letcc rather than 'app (which represent function application) to represent the operator and operand.


So I think your test case should wrote like 
`(value-of-cps  '(letcc (throw (var 0) (const 3)))  (empty-env) (empty-k))`
so that it can evaluate at the original files.


Again, this lexical-address representation is really annoying. When I'm doing this, I just follow the basic CPS rules to make it meaning-preserving and doesn't think much about the semantics. 
Also, I bet there is some bugs like apply extra continuation call on these early steps but fixed on the final file. Wish that doesn't cause you some troubles~

If you got any other questions, feel free to chat with me!

**Comment by jellyr** [comment]
oh， i know！  your code is right , 
https://github.com/chzihan/A596/blob/bbf8047eb4dfb798175c1800465f6d8b6a460985/HW7/a7_01.rkt#L56
should be 
`(k^ k)`
so , your code does not have any problem.

my problem is that i want to support :
```
(lex
 `(let/cc k
       (k 3))
 `())

(value-of-cps
   '(letcc (app (var 0) (const 3)))
   (empty-env)
   (empty-k))
```

so dig into the code , i finally get the result:

add this case : 
```
[`(app (var ,x) ,rand) (value-of-cps `(var ,x) env
                                         (lambda (v1)(value-of-cps rand env
                                                                   (lambda (v2)(v1 v2)))))]
```

then both 
(value-of-cps '(letcc (throw (var 0) (const 3))) (empty-env) (empty-k))
and
(value-of-cps
   '(letcc (app (var 0) (const 3)))
   (empty-env)
   (empty-k))
are support!

happy!

BTW: 
       I taught my self programming, and not live in America, just want to train myself by Daniel P. Friedman's homework~

**Comment by chzihan** [comment]
Cool man!  I think you already found the webpage of this course. 
[https://cgi.soic.indiana.edu/~c311/doku.php?id=assignments](url)
Be careful, the assignment page will be locked if semester ends (and become public at next time).
I may upload those demonstration code used in class later, wish it's useful.

**Comment by jellyr** [comment]
thank you for providing all the class material (pdf, source code used in class etc) ,  and I already saved the webpage for homework~   thank you for reminding me the  expire date of  assignment page.
